### ISSUE TITLE
How can i scrape only one post link ? 

### ISSUE THREAD

**Issue by serhatgksu** [MickaelWalter/wp-json-scraper#3]
How can I export only the post in the link you specified instead of all the posts?

Like;
`.\WPJsonScraper.py --one-post "https://guvenliksistemleri.net/en-iyi-kaliteli-guvenlik-kamerasi-markalari/"`

**Comment by MickaelWalter** [comment]
Hi,

At the moment you can't. I'm working on this in a new interactive mode (because I'm not a huge fan of a long command line). It is possible to only export one post using the interactive mode on develop branch, but as this is under development it is not stable yet and won't be for at least the next few weeks.

In the meantime, a workaround may be possible using the -S option specifying the post title. Or you can extract the content as a json by going to hxxp://example.com/wp-json/wp/v2/posts/post ID.

**Comment by MickaelWalter** [comment]
Hi,

This feature has been implemented in [interactive mode](https://github.com/MickaelWalter/wp-json-scraper/blob/master/doc/Interactive.md).

To find the post id, you may use the `search` command and then the `fetch` command. You can also export it as JSON if you want the full content (meta-data + body).
